/**
 * seed_mugs.js
 * Script to seed 30+ realistic mug products into MongoDB.
 */

const connectDB = require('./lib/mongodb');
const Product = require('./models/Product');

const mugs = [
    {
        name: "Milton Kool Trendy Plastic Mug",
        slug: "milton-kool-trendy-plastic-mug-500ml",
        brand: "Milton",
        description: "Durable and stylish plastic mug, perfect for daily use in hostels.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "500ml",
        colors: ["Red", "Blue", "Green"],
        image: "https://images.unsplash.com/photo-1542601906990-b4d3fb75bb21?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1542601906990-b4d3fb75bb21?auto=format&fit=crop&w=800&q=80"],
        price: 149,
        originalPrice: 199,
        discount: "25% OFF",
        stock: 100,
        rating: 4.5,
        featured: true,
        trending: true
    },
    {
        name: "Cello Stainless Steel Coffee Mug",
        slug: "cello-stainless-steel-coffee-mug-350ml",
        brand: "Cello",
        description: "Premium stainless steel mug with a comfortable grip for your morning coffee.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Stainless Steel",
        capacity: "350ml",
        colors: ["Silver", "Black"],
        image: "https://images.unsplash.com/photo-1577935760235-08e1e7798363?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1577935760235-08e1e7798363?auto=format&fit=crop&w=800&q=80"],
        price: 349,
        originalPrice: 499,
        discount: "30% OFF",
        stock: 50,
        rating: 4.8,
        featured: true,
        trending: false
    },
    {
        name: "Borosil Vision Glass Mug",
        slug: "borosil-vision-glass-mug-300ml",
        brand: "Borosil",
        description: "Classic borosilicate glass mug, heat resistant and elegant.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Borosilicate Glass",
        capacity: "300ml",
        colors: ["Transparent"],
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80"],
        price: 299,
        originalPrice: 350,
        discount: "15% OFF",
        stock: 75,
        rating: 4.7,
        featured: false,
        trending: true
    },
    {
        name: "Nayasa Bathroom Mug Premium",
        slug: "nayasa-bathroom-mug-1l",
        brand: "Nayasa",
        description: "Large capacity bathroom mug made from high-quality plastic.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "1L",
        colors: ["Blue", "Pink", "Ivory"],
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80"],
        price: 89,
        originalPrice: 120,
        discount: "25% OFF",
        stock: 200,
        rating: 4.3,
        featured: false,
        trending: false
    },
    {
        name: "Home Puff Insulated Travel Mug",
        slug: "home-puff-insulated-travel-mug-450ml",
        brand: "Home Puff",
        description: "Double-walled vacuum insulated mug that keeps drinks hot/cold for 6 hours.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Stainless Steel",
        capacity: "450ml",
        colors: ["Matte Black", "Ocean Blue"],
        image: "https://images.unsplash.com/photo-1517256011271-103ad00e69f8?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1517256011271-103ad00e69f8?auto=format&fit=crop&w=800&q=80"],
        price: 899,
        originalPrice: 1299,
        discount: "30% OFF",
        stock: 30,
        rating: 4.9,
        featured: true,
        trending: true
    },
    {
        name: "Tupperware T-Mug Set of 2",
        slug: "tupperware-t-mug-set-of-2-350ml",
        brand: "Tupperware",
        description: "Classic Tupperware mugs, microwave safe and highly durable.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "350ml",
        colors: ["Multi"],
        image: "https://images.unsplash.com/photo-1576091160550-2173bdd99623?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1576091160550-2173bdd99623?auto=format&fit=crop&w=800&q=80"],
        price: 599,
        originalPrice: 750,
        discount: "20% OFF",
        stock: 40,
        rating: 4.6,
        featured: false,
        trending: false
    },
    {
        name: "Milton Steel Mug with Lid",
        slug: "milton-steel-mug-with-lid-400ml",
        brand: "Milton",
        description: "Stainless steel mug with a spill-proof lid, ideal for office or study sessions.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Stainless Steel",
        capacity: "400ml",
        colors: ["Red", "Silver"],
        image: "https://images.unsplash.com/photo-1577935760235-08e1e7798363?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1577935760235-08e1e7798363?auto=format&fit=crop&w=800&q=80"],
        price: 449,
        originalPrice: 550,
        discount: "18% OFF",
        stock: 60,
        rating: 4.5,
        featured: true,
        trending: false
    },
    {
        name: "Cello Printed Ceramic Mug",
        slug: "cello-printed-ceramic-mug-330ml",
        brand: "Cello",
        description: "Beautifully printed ceramic mug with inspirational quotes.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Ceramic",
        capacity: "330ml",
        colors: ["White", "Yellow"],
        image: "https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80"],
        price: 199,
        originalPrice: 299,
        discount: "33% OFF",
        stock: 120,
        rating: 4.4,
        featured: false,
        trending: true
    },
    {
        name: "Nayasa Measuring Mug",
        slug: "nayasa-measuring-mug-1.5l",
        brand: "Nayasa",
        description: "Accurate measuring mug for kitchen use, transparent with clear markings.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "1.5L",
        colors: ["Transparent"],
        image: "https://images.unsplash.com/photo-1590604518041-945763266e74?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1590604518041-945763266e74?auto=format&fit=crop&w=800&q=80"],
        price: 129,
        originalPrice: 150,
        discount: "14% OFF",
        stock: 80,
        rating: 4.2,
        featured: false,
        trending: false
    },
    {
        name: "Borosil Coffee Mug Set of 6",
        slug: "borosil-coffee-mug-set-of-6-200ml",
        brand: "Borosil",
        description: "Set of 6 elegant borosilicate glass mugs for your guests.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Borosilicate Glass",
        capacity: "200ml",
        colors: ["Transparent"],
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80"],
        price: 1199,
        originalPrice: 1500,
        discount: "20% OFF",
        stock: 25,
        rating: 4.8,
        featured: true,
        trending: true
    },
    {
        name: "Home Puff Mini Espresso Mug",
        slug: "home-puff-mini-espresso-mug-150ml",
        brand: "Home Puff",
        description: "Cute mini mug for espresso lovers, ceramic build.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Ceramic",
        capacity: "150ml",
        colors: ["Brown", "Beige"],
        image: "https://images.unsplash.com/photo-1517256011271-103ad00e69f8?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1517256011271-103ad00e69f8?auto=format&fit=crop&w=800&q=80"],
        price: 249,
        originalPrice: 350,
        discount: "28% OFF",
        stock: 90,
        rating: 4.6,
        featured: false,
        trending: false
    },
    {
        name: "Tupperware Large Soup Mug",
        slug: "tupperware-large-soup-mug-600ml",
        brand: "Tupperware",
        description: "Sturdy large mug with handle, perfect for soup or large coffee.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "600ml",
        colors: ["Orange", "Blue"],
        image: "https://images.unsplash.com/photo-1576091160550-2173bdd99623?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1576091160550-2173bdd99623?auto=format&fit=crop&w=800&q=80"],
        price: 499,
        originalPrice: 600,
        discount: "17% OFF",
        stock: 55,
        rating: 4.7,
        featured: false,
        trending: true
    },
    {
        name: "Milton Plastic Bathroom Mug",
        slug: "milton-plastic-bathroom-mug-1.5l",
        brand: "Milton",
        description: "Classic Milton bathroom mug, unbreakable and durable.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "1.5L",
        colors: ["Red", "Green", "Blue"],
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80"],
        price: 119,
        originalPrice: 150,
        discount: "20% OFF",
        stock: 150,
        rating: 4.4,
        featured: false,
        trending: false
    },
    {
        name: "Cello Steel Insulated Mug",
        slug: "cello-steel-insulated-mug-500ml",
        brand: "Cello",
        description: "Insulated steel mug with an airtight lid, keeps beverages fresh.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Stainless Steel",
        capacity: "500ml",
        colors: ["Black", "White"],
        image: "https://images.unsplash.com/photo-1577935760235-08e1e7798363?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1577935760235-08e1e7798363?auto=format&fit=crop&w=800&q=80"],
        price: 549,
        originalPrice: 799,
        discount: "31% OFF",
        stock: 45,
        rating: 4.7,
        featured: true,
        trending: true
    },
    {
        name: "Borosil Glass Tea Mug Premium",
        slug: "borosil-glass-tea-mug-250ml",
        brand: "Borosil",
        description: "Lightweight and strong borosilicate tea mug.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Borosilicate Glass",
        capacity: "250ml",
        colors: ["Transparent"],
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80"],
        price: 249,
        originalPrice: 300,
        discount: "17% OFF",
        stock: 100,
        rating: 4.5,
        featured: false,
        trending: false
    },
    {
        name: "Nayasa Mini Mug for Kids",
        slug: "nayasa-mini-mug-for-kids-200ml",
        brand: "Nayasa",
        description: "Small colorful mugs for kids, made from safe food-grade plastic.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "200ml",
        colors: ["Yellow", "Orange", "Cyan"],
        image: "https://images.unsplash.com/photo-1542601906990-b4d3fb75bb21?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1542601906990-b4d3fb75bb21?auto=format&fit=crop&w=800&q=80"],
        price: 69,
        originalPrice: 99,
        discount: "30% OFF",
        stock: 180,
        rating: 4.1,
        featured: false,
        trending: false
    },
    {
        name: "Home Puff Ceramic Hand-Painted Mug",
        slug: "home-puff-ceramic-hand-painted-mug-350ml",
        brand: "Home Puff",
        description: "Exquisite hand-painted ceramic mug for a unique experience.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Ceramic",
        capacity: "350ml",
        colors: ["Multi-Color"],
        image: "https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80"],
        price: 399,
        originalPrice: 599,
        discount: "33% OFF",
        stock: 40,
        rating: 4.9,
        featured: true,
        trending: true
    },
    {
        name: "Tupperware Coffee to Go Mug",
        slug: "tupperware-coffee-to-go-mug-490ml",
        brand: "Tupperware",
        description: "Travel-friendly coffee mug with a secure lid and handle.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "490ml",
        colors: ["Dark Blue", "Red"],
        image: "https://images.unsplash.com/photo-1576091160550-2173bdd99623?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1576091160550-2173bdd99623?auto=format&fit=crop&w=800&q=80"],
        price: 649,
        originalPrice: 850,
        discount: "24% OFF",
        stock: 35,
        rating: 4.7,
        featured: false,
        trending: false
    },
    {
        name: "Milton Insulated Steel Mug",
        slug: "milton-insulated-steel-mug-300ml",
        brand: "Milton",
        description: "Compact insulated mug for small servings of tea or coffee.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Stainless Steel",
        capacity: "300ml",
        colors: ["Silver"],
        image: "https://images.unsplash.com/photo-1577935760235-08e1e7798363?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1577935760235-08e1e7798363?auto=format&fit=crop&w=800&q=80"],
        price: 399,
        originalPrice: 499,
        discount: "20% OFF",
        stock: 70,
        rating: 4.6,
        featured: false,
        trending: false
    },
    {
        name: "Cello Opalware Mug Set of 2",
        slug: "cello-opalware-mug-set-of-2-300ml",
        brand: "Cello",
        description: "Elegant white opalware mugs, scratch resistant and beautiful.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Opalware",
        capacity: "300ml",
        colors: ["White"],
        image: "https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80"],
        price: 349,
        originalPrice: 450,
        discount: "22% OFF",
        stock: 65,
        rating: 4.4,
        featured: false,
        trending: false
    },
    {
        name: "Borosil Larah Mug Set of 6",
        slug: "borosil-larah-mug-set-of-6-300ml",
        brand: "Borosil",
        description: "Premium opalware mugs from Larah by Borosil.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Opalware",
        capacity: "300ml",
        colors: ["White with Patterns"],
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80"],
        price: 899,
        originalPrice: 1100,
        discount: "18% OFF",
        stock: 40,
        rating: 4.7,
        featured: true,
        trending: false
    },
    {
        name: "Nayasa Premium Coffee Mug",
        slug: "nayasa-premium-coffee-mug-400ml",
        brand: "Nayasa",
        description: "BPA-free plastic coffee mug with a premium finish.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "400ml",
        colors: ["Brown", "Cream"],
        image: "https://images.unsplash.com/photo-1542601906990-b4d3fb75bb21?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1542601906990-b4d3fb75bb21?auto=format&fit=crop&w=800&q=80"],
        price: 159,
        originalPrice: 199,
        discount: "20% OFF",
        stock: 110,
        rating: 4.2,
        featured: false,
        trending: false
    },
    {
        name: "Home Puff Bamboo Fiber Mug",
        slug: "home-puff-bamboo-fiber-mug-400ml",
        brand: "Home Puff",
        description: "Eco-friendly mug made from sustainable bamboo fiber.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Bamboo Fiber",
        capacity: "400ml",
        colors: ["Natural Green", "Wood"],
        image: "https://images.unsplash.com/photo-1517256011271-103ad00e69f8?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1517256011271-103ad00e69f8?auto=format&fit=crop&w=800&q=80"],
        price: 499,
        originalPrice: 699,
        discount: "28% OFF",
        stock: 50,
        rating: 4.8,
        featured: true,
        trending: true
    },
    {
        name: "Tupperware One-Touch Mug",
        slug: "tupperware-one-touch-mug-350ml",
        brand: "Tupperware",
        description: "Mug with a one-touch opening lid, very convenient for busy students.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "350ml",
        colors: ["Purple", "Black"],
        image: "https://images.unsplash.com/photo-1576091160550-2173bdd99623?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1576091160550-2173bdd99623?auto=format&fit=crop&w=800&q=80"],
        price: 749,
        originalPrice: 950,
        discount: "21% OFF",
        stock: 30,
        rating: 4.6,
        featured: false,
        trending: false
    },
    {
        name: "Milton Glass Mug with Handle",
        slug: "milton-glass-mug-with-handle-350ml",
        brand: "Milton",
        description: "Simple yet elegant glass mug for daily use.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Glass",
        capacity: "350ml",
        colors: ["Transparent"],
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80"],
        price: 199,
        originalPrice: 250,
        discount: "20% OFF",
        stock: 90,
        rating: 4.4,
        featured: false,
        trending: false
    },
    {
        name: "Cello Copper Finished Mug",
        slug: "cello-copper-finished-mug-400ml",
        brand: "Cello",
        description: "Stainless steel mug with a premium copper finish on the outside.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Stainless Steel",
        capacity: "400ml",
        colors: ["Copper"],
        image: "https://images.unsplash.com/photo-1577935760235-08e1e7798363?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1577935760235-08e1e7798363?auto=format&fit=crop&w=800&q=80"],
        price: 699,
        originalPrice: 999,
        discount: "30% OFF",
        stock: 20,
        rating: 4.9,
        featured: true,
        trending: false
    },
    {
        name: "Borosil Hot 'n' Fresh Mug",
        slug: "borosil-hot-n-fresh-mug-420ml",
        brand: "Borosil",
        description: "Double-walled glass mug that keeps your tea hot for longer.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Borosilicate Glass",
        capacity: "420ml",
        colors: ["Transparent"],
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80"],
        price: 499,
        originalPrice: 650,
        discount: "23% OFF",
        stock: 45,
        rating: 4.7,
        featured: false,
        trending: true
    },
    {
        name: "Nayasa Bathroom Mug Large",
        slug: "nayasa-bathroom-mug-large-2l",
        brand: "Nayasa",
        description: "Extra-large bathroom mug for varied needs.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "2L",
        colors: ["Red", "Blue"],
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80"],
        price: 149,
        originalPrice: 199,
        discount: "25% OFF",
        stock: 100,
        rating: 4.3,
        featured: false,
        trending: false
    },
    {
        name: "Home Puff Metallic Coffee Mug",
        slug: "home-puff-metallic-coffee-mug-380ml",
        brand: "Home Puff",
        description: "Stylish metallic finish coffee mug for the modern hostel room.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Stainless Steel",
        capacity: "380ml",
        colors: ["Rose Gold", "Space Grey"],
        image: "https://images.unsplash.com/photo-1517256011271-103ad00e69f8?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1517256011271-103ad00e69f8?auto=format&fit=crop&w=800&q=80"],
        price: 799,
        originalPrice: 1099,
        discount: "27% OFF",
        stock: 35,
        rating: 4.8,
        featured: true,
        trending: true
    },
    {
        name: "Tupperware Stackable Mug Set",
        slug: "tupperware-stackable-mug-set-4-pcs",
        brand: "Tupperware",
        description: "Set of 4 stackable mugs, space-saving and extremely useful.",
        category: "Home",
        subcategory: "Kitchen",
        section: "Tableware",
        material: "Plastic",
        capacity: "350ml each",
        colors: ["Rainbow"],
        image: "https://images.unsplash.com/photo-1576091160550-2173bdd99623?auto=format&fit=crop&w=800&q=80",
        images: ["https://images.unsplash.com/photo-1576091160550-2173bdd99623?auto=format&fit=crop&w=800&q=80"],
        price: 999,
        originalPrice: 1250,
        discount: "20% OFF",
        stock: 25,
        rating: 4.7,
        featured: true,
        trending: false
    }
];

async function seedMugs() {
    try {
        await connectDB();
        
        // Delete existing mugs to avoid duplicates if re-running
        await Product.deleteMany({ subcategory: "Kitchen", section: "Tableware" });
        console.log('🗑️ Existing mugs cleared.');

        // Insert new mugs
        await Product.insertMany(mugs);
        console.log('🌱 30 Mug products seeded successfully.');

        process.exit(0);
    } catch (error) {
        console.error('❌ Error seeding mugs:', error);
        process.exit(1);
    }
}

seedMugs();
